services:
  - type: web
    name: portfolio
    env: node
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run render-start
    envVars:
      - key: NODE_VERSION
        value: 18 